---

- name: Configuration of my laptop
  hosts: laptops
  user: kushner
  vars_files:
    - vars/config.yml
    - vars/common_packages.yml
    - vars/arch_packages.yml
  tasks:
    - debug: msg={{ansible_os_family}}
  roles:
    - { role: dev-packages, sudo: true }
    - { role: gui-packages, sudo: true }
    - { role: aur-packages, sudo: true, when: ansible_os_family == "Archlinux"}
