- name: Install dev applications using apt
  apt:
      name={{ item }} state=present
  with_items: "{{ common_install }}"
  when: ansible_os_family == "Debian"

- name: Install dev applications using pacman
  pacman:
      name={{ item }} state=present
  with_items: "{{ common_install }}"
  when: ansible_os_family == "Archlinux"

- name: Copy vim configuration
  template:
      src=vimrc.j2 dest=/home/{{ config.username }}/.vimrc force=no owner={{ config.username }} group={{ config.username }}
